try {
    
    throw new Error ("seu c√≥digo tem um problema");
} catch (e) {
    console.log(e.name + ": " + e.message);
}